// File generated by the FlutterFire CLI.
// To regenerate this file, run:
// flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_WLn9JyFMiVHh1uOVWPg-v21l4swgvGE',
    appId: '1:1067226290728:web:ondeestaoscar',
    messagingSenderId: '1067226290728',
    projectId: 'ondeestaoscar',
    authDomain: 'ondeestaoscar.firebaseapp.com',
    databaseURL: 'https://ondeestaoscar-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ondeestaoscar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_WLn9JyFMiVHh1uOVWPg-v21l4swgvGE',
    appId: '1:1067226290728:android:21a9f18fc010667836731d',
    messagingSenderId: '1067226290728',
    projectId: 'ondeestaoscar',
    databaseURL: 'https://ondeestaoscar-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ondeestaoscar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_WLn9JyFMiVHh1uOVWPg-v21l4swgvGE',
    appId: '1:1067226290728:ios:ondeestaoscar',
    messagingSenderId: '1067226290728',
    projectId: 'ondeestaoscar',
    databaseURL: 'https://ondeestaoscar-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ondeestaoscar.firebasestorage.app',
    iosBundleId: 'com.example.smartPetFeeder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_WLn9JyFMiVHh1uOVWPg-v21l4swgvGE',
    appId: '1:1067226290728:macos:ondeestaoscar',
    messagingSenderId: '1067226290728',
    projectId: 'ondeestaoscar',
    databaseURL: 'https://ondeestaoscar-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ondeestaoscar.firebasestorage.app',
    iosBundleId: 'com.example.smartPetFeeder',
  );
}

